=== hyoban/hyoban.cc/data/schema/moment.schema.json
{
  "$id": "https://hyoban.cc/data/schema/v1/moment.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "uid": {
      "type": "string",
      "pattern": "^[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "occurredAt": {
      "anyOf": [
        {
          "type": "string",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}$"
        },
        {
          "type": "string",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}(?::\\d{2})?(?:Z|[+-]\\d{2}:\\d{2})$"
        }
      ]
    },
    "places": {
      "default": [],
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$"
      }
    },
    "text": {
      "type": "string"
    },
    "hidden": {
      "default": false,
      "type": "boolean"
    },
    "media": {
      "default": [],
      "type": "array",
      "items": {
        "oneOf": [
          {
            "type": "object",
            "properties": {
              "uid": {
                "type": "string",
                "pattern": "^[0-9A-HJKMNP-TV-Z]{26}$"
              },
              "alt": {
                "default": "",
                "type": "string"
              },
              "takenAt": {
                "type": "string",
                "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}(?::\\d{2})?(?:Z|[+-]\\d{2}:\\d{2})$"
              },
              "local": {
                "type": "object",
                "properties": {
                  "uri": {
                    "type": "string",
                    "minLength": 1
                  },
                  "videoUri": {
                    "type": "string",
                    "minLength": 1
                  },
                  "sha256": {
                    "type": "string",
                    "pattern": "^[0-9a-f]{64}$"
                  },
                  "copied": {
                    "default": false,
                    "type": "boolean"
                  }
                },
                "required": [
                  "uri"
                ],
                "additionalProperties": {}
              },
              "type": {
                "type": "string",
                "const": "image"
              },
              "width": {
                "type": "integer",
                "exclusiveMinimum": 0,
                "maximum": 9007199254740991
              },
              "height": {
                "type": "integer",
                "exclusiveMinimum": 0,
                "maximum": 9007199254740991
              },
              "published": {
                "type": "object",
                "properties": {
                  "key": {
                    "type": "string",
                    "minLength": 1
                  },
                  "contentType": {
                    "type": "string",
                    "format": "starts_with",
                    "pattern": "^image\\/.*"
                  },
                  "bytes": {
                    "type": "integer",
                    "exclusiveMinimum": 0,
                    "maximum": 9007199254740991
                  },
                  "etag": {
                    "type": "string",
                    "pattern": "^[0-9a-f]{32}$"
                  },
                  "width": {
                    "type": "integer",
                    "exclusiveMinimum": 0,
                    "maximum": 9007199254740991
                  },
                  "height": {
                    "type": "integer",
                    "exclusiveMinimum": 0,
                    "maximum": 9007199254740991
                  },
                  "variants": {
                    "default": [],
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "key": {
                          "type": "string",
                          "minLength": 1
                        },
                        "contentType": {
                          "type": "string",
                          "minLength": 1
                        },
                        "bytes": {
                          "type": "integer",
                          "exclusiveMinimum": 0,
                          "maximum": 9007199254740991
                        },
                        "etag": {
                          "type": "string",
                          "pattern": "^[0-9a-f]{32}$"
                        },
                        "width": {
                          "type": "integer",
                          "exclusiveMinimum": 0,
                          "maximum": 9007199254740991
                        },
                        "height": {
                          "type": "integer",
                          "exclusiveMinimum": 0,
                          "maximum": 9007199254740991
                        }
                      },
                      "required": [
                        "key",
                        "contentType",
                        "bytes",
                        "etag",
                        "width",
                        "height"
                      ],
                      "additionalProperties": {}
                    }
                  }
                },
                "required": [
                  "key",
                  "contentType",
                  "bytes",
                  "etag",
                  "width",
                  "height"
                ],
                "additionalProperties": {}
              }
            },
            "required": [
              "uid",
              "type",
              "width",
              "height"
            ],
            "additionalProperties": {}
          },
          {
            "type": "object",
            "properties": {
              "uid": {
                "type": "string",
                "pattern": "^[0-9A-HJKMNP-TV-Z]{26}$"
              },
              "alt": {
                "default": "",
                "type": "string"
              },
              "takenAt": {
                "type": "string",
                "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}(?::\\d{2})?(?:Z|[+-]\\d{2}:\\d{2})$"
              },
              "local": {
                "type": "object",
                "properties": {
                  "uri": {
                    "type": "string",
                    "minLength": 1
                  },
                  "videoUri": {
                    "type": "string",
                    "minLength": 1
                  },
                  "sha256": {
                    "type": "string",
                    "pattern": "^[0-9a-f]{64}$"
                  },
                  "copied": {
                    "default": false,
                    "type": "boolean"
                  }
                },
                "required": [
                  "uri"
                ],
                "additionalProperties": {}
              },
              "type": {
                "type": "string",
                "const": "live-photo"
              },
              "width": {
                "type": "integer",
                "exclusiveMinimum": 0,
                "maximum": 9007199254740991
              },
              "height": {
                "type": "integer",
                "exclusiveMinimum": 0,
                "maximum": 9007199254740991
              },
              "published": {
                "type": "object",
                "properties": {
                  "key": {
                    "type": "string",
                    "minLength": 1
                  },
                  "contentType": {
                    "type": "string",
                    "format": "starts_with",
                    "pattern": "^image\\/.*"
                  },
                  "bytes": {
                    "type": "integer",
                    "exclusiveMinimum": 0,
                    "maximum": 9007199254740991
                  },
                  "etag": {
                    "type": "string",
                    "pattern": "^[0-9a-f]{32}$"
                  },
                  "width": {
                    "type": "integer",
                    "exclusiveMinimum": 0,
                    "maximum": 9007199254740991
                  },
                  "height": {
                    "type": "integer",
                    "exclusiveMinimum": 0,
                    "maximum": 9007199254740991
                  },
                  "variants": {
                    "default": [],
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "key": {
                          "type": "string",
                          "minLength": 1
                        },
                        "contentType": {
                          "type": "string",
                          "minLength": 1
                        },
                        "bytes": {
                          "type": "integer",
                          "exclusiveMinimum": 0,
                          "maximum": 9007199254740991
                        },
                        "etag": {
                          "type": "string",
                          "pattern": "^[0-9a-f]{32}$"
                        },
                        "width": {
                          "type": "integer",
                          "exclusiveMinimum": 0,
                          "maximum": 9007199254740991
                        },
                        "height": {
                          "type": "integer",
                          "exclusiveMinimum": 0,
                          "maximum": 9007199254740991
                        }
                      },
                      "required": [
                        "key",
                        "contentType",
                        "bytes",
                        "etag",
                        "width",
                        "height"
                      ],
                      "additionalProperties": {}
                    }
                  },
                  "video": {
                    "type": "object",
                    "properties": {
                      "key": {
                        "type": "string",
                        "minLength": 1
                      },
                      "contentType": {
                        "type": "string",
                        "format": "starts_with",
                        "pattern": "^video\\/.*"
                      },
                      "bytes": {
                        "type": "integer",
                        "exclusiveMinimum": 0,
                        "maximum": 9007199254740991
                      },
                      "etag": {
                        "type": "string",
                        "pattern": "^[0-9a-f]{32}$"
                      }
                    },
                    "required": [
                      "key",
                      "contentType",
                      "bytes",
                      "etag"
                    ],
                    "additionalProperties": {}
                  }
                },
                "required": [
                  "key",
                  "contentType",
                  "bytes",
                  "etag",
                  "width",
                  "height",
                  "video"
                ],
                "additionalProperties": {}
              }
            },
            "required": [
              "uid",
              "type",
              "width",
              "height"
            ],
            "additionalProperties": {}
          },
          {
            "type": "object",
            "properties": {
              "uid": {
                "type": "string",
                "pattern": "^[0-9A-HJKMNP-TV-Z]{26}$"
              },
              "alt": {
                "default": "",
                "type": "string"
              },
              "takenAt": {
                "type": "string",
                "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}(?::\\d{2})?(?:Z|[+-]\\d{2}:\\d{2})$"
              },
              "local": {
                "type": "object",
                "properties": {
                  "uri": {
                    "type": "string",
                    "minLength": 1
                  },
                  "videoUri": {
                    "type": "string",
                    "minLength": 1
                  },
                  "sha256": {
                    "type": "string",
                    "pattern": "^[0-9a-f]{64}$"
                  },
                  "copied": {
                    "default": false,
                    "type": "boolean"
                  }
                },
                "required": [
                  "uri"
                ],
                "additionalProperties": {}
              },
              "type": {
                "type": "string",
                "const": "video"
              },
              "width": {
                "type": "integer",
                "exclusiveMinimum": 0,
                "maximum": 9007199254740991
              },
              "height": {
                "type": "integer",
                "exclusiveMinimum": 0,
                "maximum": 9007199254740991
              },
              "published": {
                "type": "object",
                "properties": {
                  "key": {
                    "type": "string",
                    "minLength": 1
                  },
                  "contentType": {
                    "type": "string",
                    "format": "starts_with",
                    "pattern": "^video\\/.*"
                  },
                  "bytes": {
                    "type": "integer",
                    "exclusiveMinimum": 0,
                    "maximum": 9007199254740991
                  },
                  "etag": {
                    "type": "string",
                    "pattern": "^[0-9a-f]{32}$"
                  },
                  "poster": {
                    "type": "object",
                    "properties": {
                      "key": {
                        "type": "string",
                        "minLength": 1
                      },
                      "contentType": {
                        "type": "string",
                        "format": "starts_with",
                        "pattern": "^image\\/.*"
                      },
                      "bytes": {
                        "type": "integer",
                        "exclusiveMinimum": 0,
                        "maximum": 9007199254740991
                      },
                      "etag": {
                        "type": "string",
                        "pattern": "^[0-9a-f]{32}$"
                      },
                      "width": {
                        "type": "integer",
                        "exclusiveMinimum": 0,
                        "maximum": 9007199254740991
                      },
                      "height": {
                        "type": "integer",
                        "exclusiveMinimum": 0,
                        "maximum": 9007199254740991
                      },
                      "variants": {
                        "default": [],
                        "type": "array",
                        "items": {
                          "type": "object",
                          "properties": {
                            "key": {
                              "type": "string",
                              "minLength": 1
                            },
                            "contentType": {
                              "type": "string",
                              "minLength": 1
                            },
                            "bytes": {
                              "type": "integer",
                              "exclusiveMinimum": 0,
                              "maximum": 9007199254740991
                            },
                            "etag": {
                              "type": "string",
                              "pattern": "^[0-9a-f]{32}$"
                            },
                            "width": {
                              "type": "integer",
                              "exclusiveMinimum": 0,
                              "maximum": 9007199254740991
                            },
                            "height": {
                              "type": "integer",
                              "exclusiveMinimum": 0,
                              "maximum": 9007199254740991
                            }
                          },
                          "required": [
                            "key",
                            "contentType",
                            "bytes",
                            "etag",
                            "width",
                            "height"
                          ],
                          "additionalProperties": {}
                        }
                      }
                    },
                    "required": [
                      "key",
                      "contentType",
                      "bytes",
                      "etag",
                      "width",
                      "height"
                    ],
                    "additionalProperties": {}
                  }
                },
                "required": [
                  "key",
                  "contentType",
                  "bytes",
                  "etag"
                ],
                "additionalProperties": {}
              }
            },
            "required": [
              "uid",
              "type"
            ],
            "additionalProperties": {}
          }
        ]
      }
    },
    "trip": {
      "type": "string",
      "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$"
    },
    "published": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "pattern": "^(\\d{4})\\/(\\d{2})\\/(\\d{2})-(\\d{2})-([a-z0-9]+(?:-[a-z0-9]+)*)$"
        },
        "slug": {
          "type": "string",
          "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$"
        },
        "order": {
          "type": "integer",
          "exclusiveMinimum": 0,
          "maximum": 9007199254740991
        },
        "at": {
          "type": "string",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}(?::\\d{2})?(?:Z|[+-]\\d{2}:\\d{2})$"
        }
      },
      "required": [
        "id",
        "slug",
        "order",
        "at"
      ],
      "additionalProperties": {}
    },
    "createdAt": {
      "type": "string",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}(?::\\d{2})?(?:Z|[+-]\\d{2}:\\d{2})$"
    },
    "updatedAt": {
      "type": "string",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}(?::\\d{2})?(?:Z|[+-]\\d{2}:\\d{2})$"
    }
  },
  "required": [
    "uid",
    "occurredAt",
    "text",
    "createdAt",
    "updatedAt"
  ],
  "additionalProperties": {}
}

=== hyoban/hyoban.cc/data/moments/2026/06/01KV4T83209NMMTT1R9NVB25D3.json
{
  "uid": "01KV4T83209NMMTT1R9NVB25D3",
  "occurredAt": "2026-06-15T12:57:12+08:00",
  "places": [],
  "text": "2026 w24 莫干山\n\n周六去的时候大雨磅礴，啥也干不了只能吃饭然后在民宿待着打牌。迎来了周日晴天之后自然是自驾转山，山里的好环境让人放松。 返程之前我用三脚架和相机与朋友们拍了一张合影，在海底捞聚餐的时候打印成了照片。我很久没摸过照片了，我突然想把很多之前拍的以后拍的照片都打印出来。 我以前是对拍照很无感的，觉得很麻烦，且自己不上相。但是相机按下快门的感觉带来了很多情绪价值，就让我逐渐喜欢上拍照。也许我的三分钟热度无法把这个爱好玩的很专业，但这已经足够了。",
  "hidden": true,
  "media": [
    {
      "uid": "01KV4T83212WVY42N1T899HF5T",
      "type": "image",
      "alt": "",
      "width": 1620,
      "height": 1080,
      "published": {
        "key": "moments/2026/06/15-02-mo-gan-shan/mo-gan-shan.webp",
        "contentType": "image/webp",
        "bytes": 588452,
        "etag": "5a85f632e2c38293314a34b7ac26aed0",
        "width": 1620,
        "height": 1080,
        "variants": [
          {
            "key": "moments/2026/06/15-02-mo-gan-shan/mo-gan-shan-480w.webp",
            "contentType": "image/webp",
            "bytes": 45980,
            "etag": "80cd50ccdcdef401a1c068200be9d3bc",
            "width": 480,
            "height": 320
          },
          {
            "key": "moments/2026/06/15-02-mo-gan-shan/mo-gan-shan-960w.webp",
            "contentType": "image/webp",
            "bytes": 153962,
            "etag": "42d9496a26e396059289bbab75b54b47",
            "width": 960,
            "height": 640
          }
        ]
      }
    },
    {
      "uid": "01KV4T8322XASXT13RHVP3Z80Q",
      "type": "image",
      "alt": "",
      "width": 1620,
      "height": 1080,
      "published": {
        "key": "moments/2026/06/15-02-mo-gan-shan/mo-gan-shan-2.webp",
        "contentType": "image/webp",
        "bytes": 535770,
        "etag": "6d6b0b23c721698472a86fadbcdf1c4c",
        "width": 1620,
        "height": 1080,
        "variants": [
          {
            "key": "moments/2026/06/15-02-mo-gan-shan/mo-gan-shan-2-480w.webp",
            "contentType": "image/webp",
            "bytes": 43686,
            "etag": "9d68ed843e99e4df7eabfc038da6c8b2",
            "width": 480,
            "height": 320
          },
          {
            "key": "moments/2026/06/15-02-mo-gan-shan/mo-gan-shan-2-960w.webp",
            "contentType": "image/webp",
            "bytes": 143476,
            "etag": "422a8bbd78ef9408c84b42336592f62c",
            "width": 960,
            "height": 640
          }
        ]
      }
    },
    {
      "uid": "01KV4T8323Q58DH41873NWZDVA",
      "type": "image",
      "alt": "",
      "width": 1620,
      "height": 1080,
      "published": {
        "key": "moments/2026/06/15-02-mo-gan-shan/mo-gan-shan-3.webp",
        "contentType": "image/webp",
        "bytes": 489082,
        "etag": "d449aa55e83ba62aa70f4f7af70f095e",
        "width": 1620,
        "height": 1080,
        "variants": [
          {
            "key": "moments/2026/06/15-02-mo-gan-shan/mo-gan-shan-3-480w.webp",
            "contentType": "image/webp",
            "bytes": 38378,
            "etag": "6981d19c135f6592e2f7711307bc41db",
            "width": 480,
            "height": 320
          },
          {
            "key": "moments/2026/06/15-02-mo-gan-shan/mo-gan-shan-3-960w.webp",
            "contentType": "image/webp",
            "bytes": 125558,
            "etag": "c27b2538d85a2d0f154ca3b4359f22f9",
            "width": 960,
            "height": 640
          }
        ]
      }
    },
    {
      "uid": "01KV4T83242QD2TK369Y8KBB3W",
      "type": "image",
      "alt": "",
      "width": 1620,
      "height": 1080,
      "published": {
        "key": "moments/2026/06/15-02-mo-gan-shan/mo-gan-shan-4.webp",
        "contentType": "image/webp",
        "bytes": 194188,
        "etag": "4e948a2cd3df37ae81fd91dec8eebbb1",
        "width": 1620,
        "height": 1080,
        "variants": [
          {
            "key": "moments/2026/06/15-02-mo-gan-shan/mo-gan-shan-4-480w.webp",
            "contentType": "image/webp",
            "bytes": 17422,
            "etag": "c0a13330f8144fe39b26db5d9e3fb1da",
            "width": 480,
            "height": 320
          },
          {
            "key": "moments/2026/06/15-02-mo-gan-shan/mo-gan-shan-4-960w.webp",
            "contentType": "image/webp",
            "bytes": 46146,
            "etag": "02a7a2634cef25a47ac3819f3858a051",
            "width": 960,
            "height": 640
          }
        ]
      }
    },
    {
      "uid": "01KV4T83251RK1WEGXD97MKPQM",
      "type": "image",
      "alt": "",
      "width": 1620,
      "height": 1080,
      "published": {
        "key": "moments/2026/06/15-02-mo-gan-shan/mo-gan-shan-5.webp",
        "contentType": "image/webp",
        "bytes": 276800,
        "etag": "fd5f408fd9a8d6679a4846ec4df2e861",
        "width": 1620,
        "height": 1080,
        "variants": [
          {
            "key": "moments/2026/06/15-02-mo-gan-shan/mo-gan-shan-5-480w.webp",
            "contentType": "image/webp",
            "bytes": 30420,
            "etag": "85a810251744cdc47d0edac2a2a03ca4",
            "width": 480,
            "height": 320
          },
          {
            "key": "moments/2026/06/15-02-mo-gan-shan/mo-gan-shan-5-960w.webp",
            "contentType": "image/webp",
            "bytes": 76346,
            "etag": "ba3945d8ef8cfb93c13135af27f14ada",
            "width": 960,
            "height": 640
          }
        ]
      }
    },
    {
      "uid": "01KV4T83260QG1BFBNWPM4T92G",
      "type": "image",
      "alt": "",
      "width": 1620,
      "height": 1080,
      "published": {
        "key": "moments/2026/06/15-02-mo-gan-shan/mo-gan-shan-6.webp",
        "contentType": "image/webp",
        "bytes": 579666,
        "etag": "a37a0b5aa54f307f03535a2dc5cfdde9",
        "width": 1620,
        "height": 1080,
        "variants": [
          {
            "key": "moments/2026/06/15-02-mo-gan-shan/mo-gan-shan-6-480w.webp",
            "contentType": "image/webp",
            "bytes": 42084,
            "etag": "4c8a2ea79f4b8b207db9b6de132460c1",
            "width": 480,
            "height": 320
          },
          {
            "key": "moments/2026/06/15-02-mo-gan-shan/mo-gan-shan-6-960w.webp",
            "contentType": "image/webp",
            "bytes": 145500,
            "etag": "f5595f8b7b36f611826737f584f3fe14",
            "width": 960,
            "height": 640
          }
        ]
      }
    },
    {
      "uid": "01KV4T8327YE2NZJC2H7MBTVYD",
      "type": "image",
      "alt": "",
      "width": 1620,
      "height": 1080,
      "published": {
        "key": "moments/2026/06/15-02-mo-gan-shan/mo-gan-shan-7.webp",
        "contentType": "image/webp",
        "bytes": 355042,
        "etag": "27783835f67e81e2231928c25d8669ed",
        "width": 1620,
        "height": 1080,
        "variants": [
          {
            "key": "moments/2026/06/15-02-mo-gan-shan/mo-gan-shan-7-480w.webp",
            "contentType": "image/webp",
            "bytes": 32758,
            "etag": "1bd08caf7e7b8e5045d043dba32a08e8",
            "width": 480,
            "height": 320
          },
          {
            "key": "moments/2026/06/15-02-mo-gan-shan/mo-gan-shan-7-960w.webp",
            "contentType": "image/webp",
            "bytes": 95980,
            "etag": "8c5c9bce708980d1bf269e846a844feb",
            "width": 960,
            "height": 640
          }
        ]
      }
    },
    {
      "uid": "01KV4T8328DMZDBC5DE4X3C76A",
      "type": "image",
      "alt": "",
      "width": 1620,
      "height": 1080,
      "published": {
        "key": "moments/2026/06/15-02-mo-gan-shan/mo-gan-shan-8.webp",
        "contentType": "image/webp",
        "bytes": 214230,
        "etag": "9f981e4b2f028b8e50142e8396d74b65",
        "width": 1620,
        "height": 1080,
        "variants": [
          {
            "key": "moments/2026/06/15-02-mo-gan-shan/mo-gan-shan-8-480w.webp",
            "contentType": "image/webp",
            "bytes": 20618,
            "etag": "479bdf92c26de60a823f6a20b0cf192b",
            "width": 480,
            "height": 320
          },
          {
            "key": "moments/2026/06/15-02-mo-gan-shan/mo-gan-shan-8-960w.webp",
            "contentType": "image/webp",
            "bytes": 54422,
            "etag": "e2ea58c925f88fb84b8f5e1f6263e458",
            "width": 960,
            "height": 640
          }
        ]
      }
    },
    {
      "uid": "01KV4T83291FR3MHFZCPY1BN8T",
      "type": "image",
      "alt": "",
      "width": 1620,
      "height": 1080,
      "published": {
        "key": "moments/2026/06/15-02-mo-gan-shan/mo-gan-shan-9.webp",
        "contentType": "image/webp",
        "bytes": 324246,
        "etag": "0e4f465024fb498d4fa9ed3bd306e9a3",
        "width": 1620,
        "height": 1080,
        "variants": [
          {
            "key": "moments/2026/06/15-02-mo-gan-shan/mo-gan-shan-9-480w.webp",
            "contentType": "image/webp",
            "bytes": 30302,
            "etag": "a0cd69976688d5af8bf355efb76775c0",
            "width": 480,
            "height": 320
          },
          {
            "key": "moments/2026/06/15-02-mo-gan-shan/mo-gan-shan-9-960w.webp",
            "contentType": "image/webp",
            "bytes": 84106,
            "etag": "a2cab23cc51e2ba826af804048aa683e",
            "width": 960,
            "height": 640
          }
        ]
      }
    }
  ],
  "published": {
    "id": "2026/06/15-02-mo-gan-shan",
    "slug": "mo-gan-shan",
    "order": 2,
    "at": "2026-07-30T08:12:13+08:00"
  },
  "createdAt": "2026-06-15T12:57:12+08:00",
  "updatedAt": "2026-09-03T10:44:40+08:00"
}
